version: '3'
services:
  builder:
    build:
      context: ./
      dockerfile: Dockerfile.build
    volumes:
      - ./blog/:/usr/src/app/blog:ro
      - ./dist/:/usr/src/app/dist:rw
      
  website:
    build:
      context: ./
      dockerfile: Dockerfile.deploy
    volumes:
      - ./dist/:/usr/share/nginx/html:ro
    ports:
      - 8080:80
    depends_on:
      - builder