version: '3'

networks:
    proxy:
        external: true

services:
  builder:
    build:
      context: ./
      dockerfile: Dockerfile.build
    volumes:
      - /data/posts:/usr/src/app/blog:ro
      - ./dist/:/usr/src/app/dist:rw

  website:
    build:
      context: ./
      dockerfile: Dockerfile.deploy
    volumes:
      - ./dist/:/usr/share/nginx/html:ro
    depends_on:
      - builder
    labels:
      - traefik.enable=true
      - traefik.http.routers.static-website.rule=Host("simon.gavris.dev")
      - traefik.http.routers.static-website.entrypoints=websecure
      - traefik.http.routers.static-website.tls.certresolver=defaultresolver
    networks:
      - proxy