version: '3'

networks:
    proxy:
        external: true

services:
  builder:
    build:
      context: ./
      dockerfile: Dockerfile.build
    volumes:
      - ./blog/:/usr/src/app/blog:ro
      - ./dist/:/usr/src/app/dist:rw
      
  website:
    build:
      context: ./
      dockerfile: Dockerfile.deploy
    volumes:
      - ./dist/:/usr/share/nginx/html:ro
    ports:
      - 8080:80
    depends_on:
      - builder
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:blog.bblbrx.de
      - traefik.docker.network=proxy
      - traefik.port=80
      - traefik.protocol=http
    networks:
      - proxy